import type { ToolCall } from "./Tool.types";

export type ChatCompletionRole =
  | "developer"
  | "system"
  | "user"
  | "assistant"
  | "tool";

export type UserContentPart =
  | TextContentPart
  | ImageContentPart
  | AudioContentPart
  | FileContentPart;

export type AssistantContentPart = TextContentPart | RefusalContentPart;

export interface TextContentPart {
  type: "text";
  text: string;
}

export interface ImageContentPart {
  type: "image_url";
  image_url: {
    url: string;
    detail?: "auto" | "low" | "high";
  };
}

export interface AudioContentPart {
  type: "input_audio";
  input_audio: {
    data: string;
    format: "wav" | "mp3";
  };
}

export interface FileContentPart {
  type: "file";
  file: {
    file_data?: string;
    file_id?: string;
    file_name?: string;
  };
}

export interface RefusalContentPart {
  type: "refusal";
  refusal: string;
}

/**
 * Stricter Discriminated Union for Chat Completion Messages
 */
export type RequestMessages =
  | DeveloperMessage
  | SystemMessage
  | UserMessage
  | AssistantMessage
  | ToolMessage;

export interface DeveloperMessage {
  content: string | TextContentPart[];
  role: "developer";
  name?: string;
}

export interface SystemMessage {
  content: string | TextContentPart[];
  role: "system";
  name?: string;
}

export interface UserMessage {
  content: string | UserContentPart[];
  role: "user";
  name?: string;
}

export interface AssistantMessage {
  role: "assistant";
  audio?: { id: string };
  content?: string | AssistantContentPart[];
  name?: string;
  refusal?: string;
  reasoning_content?: string;
  tool_calls?: ToolCall[];
}

export interface ToolMessage {
  content: string | TextContentPart[];
  role: "tool";
  tool_call_id: string;
}

/**
 * Specifically for the message returned in a chat completion response.
 */
export interface ResponseMessage {
  /** The role of the messages author. */
  role: "assistant";
  /** The contents of the message. */
  content: string | null;
  /** The refusal message by the model. */
  refusal: string | null;
  /** The reasoning or thinking content by the model. */
  reasoning_content: string | null;
  /** Annotations for the message. */
  annotations?: Annotation[];
  /** Data about a previous audio response. */
  audio?: {
    data: string;
    expires_at: number;
    id: string;
    transcript: string;
  };
  /** The tool calls generated by the model. */
  tool_calls?: ToolCall[];
}

export interface Annotation {
  type: "url_citation";
  url_citation: {
    end_index: number;
    start_index: number;
    title: string;
    url: string;
  };
}
